apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dd-agent
  namespace: datadog
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dd-agent
      name: dd-agent
      namespace: datadog
    spec:
      serviceAccountName: datadog-agent
      tolerations:
        - operator: "Exists"
          key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      containers:
      - image: datadog/agent:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 1024Mi
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-cluster-secrets
                key: API_KEY
          - name: KUBERNETES
            value: "true"
          - name: SD_BACKEND
            value: docker
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups

