apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: http-metrics
    scheme: http
    scrapeTimeout: 30s
 - honorLabels: true
    interval: 30s
    port: telemetry
    scheme: http
    scrapeTimeout: 30s
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
